databaseChangeLog:

  # Example table creation
  - changeSet:
      id: 1
      author: imosia
      changes:
        - createTable:
            tableName: test_table
            columns:
              - column:
                  name: event_id
                  type: varchar(255)
                  constraints:
                    primaryKey: true
              - column:
                  name: timestamp
                  type: timestamp